### PR TITLE
ENH: Update DREAM.3D repos to 2016-07-12 develop branch.

### PR DESCRIPTION
**Pull request by fbudin69500**

### CODE REVIEW

**Comment by fbudin69500** [comment]
@thewtex please review :)

**Comment by thewtex** [comment]
+1 for the first commit. -1 for the second commit -- it is not needed and will bloat the image

**Comment by fbudin69500** [comment]
@thewtex Second commit removed.

**Comment by thewtex** [comment]
Nice, thanks!

**Pull request merged**
